### ISSUE TITLE
LambertW.jl won't precompile on Julia 0.7.0-beta2.189

### ISSUE THREAD

**Issue by goedman** [jlapeyre/LambertW.jl#11]
Hi John,

On Julia 0.7.0-beta2.189 line 213 in LambertW.jl (`@doc (@doc ω) omega = ω`) is playing up. Last Thursday (I think on beta2.135) is was fine. This is both in the package LambertW as well as in the single file inclusion in Symata (precompiling Symata will fail).

Best,
Rob

(v0.7) pkg> test LambertW
   Testing LambertW
 Resolving package versions...
    Status `/var/folders/fb/m164mwfn3v1btnrpmmyzpvqh0000gn/T/tmp8DYNEE/Manifest.toml`
  [984bce1d] LambertW v0.4.1 [`~/.julia/dev/LambertW`]
ERROR: LoadError: LoadError: MethodError: no method matching root_module(::Nothing)
Closest candidates are:
  root_module(::Module, ::Symbol) at loading.jl:897
  root_module(::Base.PkgId) at loading.jl:896
Stacktrace:
 [1] root_module(::Module, ::Symbol) at ./loading.jl:897
 [2] docm(::LineNumberNode, ::Module, ::Any) at ./docs/Docs.jl:500
 [3] @doc(::LineNumberNode, ::Module, ::Symbol) at ./boot.jl:451
 [4] include at ./boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1052
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] top-level scope at none:0
 [8] eval at ./boot.jl:319 [inlined]
 [9] eval(::Expr) at ./client.jl:399
 [10] top-level scope at ./none:3
in expression starting at /Users/rob/.julia/dev/LambertW/src/LambertW.jl:213
in expression starting at /Users/rob/.julia/dev/LambertW/src/LambertW.jl:213
ERROR: LoadError: Failed to precompile LambertW to /Users/rob/.julia/compiled/v0.7/LambertW/7mpiq.ji.

**Comment by goedman** [comment]
Very weird. Initially I noticed `using LambertW` followed by running runtests.jl (using include) worked.
Then I tried many different ways your approach, but only after many attempts and reinstalling LambertW several times I had it in the same state as you described. And now `test LambertW` in a new REPL & Pkg REPL works again. I do notice a minor change in Project.toml (uuid on 2nd line and license on 3rd line).

And now I can also precompile Symata again on the latest Julia 0.7 build!

**Comment by jlapeyre** [comment]
Weird. I am hoping the problem goes away by itself (code changes elsewhere).

**Comment by goedman** [comment]
Aah, what seems to fix it is issuing a ‘precompile’ in Pkg REPL. I’ll check if I can make it reproducible and if so file an issue.

**Comment by goedman** [comment]
Haven't seen this anymore on recent versions of 0.7 and 1.0. So you were probably right, code changes somewhere!
