### ISSUE TITLE
Support ForwardDiff's Duals

### ISSUE THREAD

**Issue by cossio** [jlapeyre/LambertW.jl#13]
I tried `ForwardDiff.derivative(LambertW.lambertw, 1.)` and got an error. 

> ERROR: MethodError: no method matching lambertw_branch_zero(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(LambertW.lambertw),Float64},Float64,1}, ::Int64)

Is there a way to make the implementation more generic to accept `Dual`s?

In the meantime I wrote a temporary patch to handle positive values.

```julia
import ForwardDiff: Dual, value, partials
using LambertW

function LambertW.lambertw(d::Dual{T}) where {T}
    x = value(d)
    @assert x ≥ 0
    f = lambertw(x)
    if x > 0
        g = lambertw(x) / x / (1 + lambertw(x))
    else
        g = one(x)
    end
    Dual{T}(f, g * partials(d))
end
```

But if `lambertw` handled arguments of type `Real`, this probably would not be necessary.

**Comment by cossio** [comment]
nice! I'll update as soon as it shows up in the registry.

**Comment by cossio** [comment]
It works for

```
ForwardDiff.derivative(LambertW.lambertw, 1.0)
```

which is already good enough for me. Thanks!

However I just want to point out that it doesn't work if you use ints,

```
ForwardDiff.derivative(LambertW.lambertw, 1)
```

I get an error:

> ERROR: MethodError: no method matching Int64(::Irrational{:ℯ})

**Comment by jlapeyre** [comment]
I would not want to make great changes to support this, because the use case seems dubious a priori. But, I just pushed a very small commit that supports `ForwardDiff.derivative(LambertW.lambertw, 1)` although the return type is `Float16`. The return type of `ForwardDiff.derivative(LambertW.lambertw, big(1))` is `BigFloat`.

**Comment by cossio** [comment]
The `Float16` return type is probably related to this: https://github.com/JuliaDiff/ForwardDiff.jl/issues/362

**Comment by jlapeyre** [comment]
Yes, certainly. It's probably because `ForwardDiff` is normally used with huge data sets.
