### ISSUE TITLE
warn -> @warn

### ISSUE THREAD

**Issue by cossio** [jlapeyre/LambertW.jl#14]
```
julia> lambertw(100., 0, 3)
ERROR: UndefVarError: warn not defined
```

Culprit line:

https://github.com/jlapeyre/LambertW.jl/blob/0af7d43b2df63bcfd991ea7649101065a5573f39/src/LambertW.jl#L158

`warn` must be replaced by `@warn` in Julia 1.0.

**Comment by AsafManela** [comment]
Thanks for writing this package!
Any chance you could release a new version as this is fixed in master?
