### ISSUE TITLE
Installation of correct version

### ISSUE THREAD

**Issue by jbrea** [jlapeyre/LambertW.jl#17]
When I add LambertW in julia 1.1 I get version 0.4.3 (which errs because of warn) instead of 0.4.4. Is this because Project.toml sets version 0.4.3?

**Comment by AsafManela** [comment]
I'm guessing it's because v0.4.4 was not registered with the new [Registrator](https://github.com/JuliaRegistries/Registrator.jl)
@jlapeyre please let me know if I can help with that process as I have a package that depends on this, thanks!

**Comment by jlapeyre** [comment]
Sure @AsafManela, if you'd like to help, I'd appreciate it. I have a backlog, and will get to it eventually, but it may take a while. Thanks!
