### ISSUE TITLE
@inline error

### ISSUE THREAD

**Issue by wielrenner** [jlapeyre/LambertW.jl#4]
*julia> using LambertW
ERROR: @inline not defined
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading C:\Users\Wouter\.julia\v0.3\LambertW\src\LambertW.jl, in expressio
n starting on line 267*

After running "using LambertW" for the second time I got no error and it works.

**Comment by jlapeyre** [comment]
This does not happen to me with Julia 0.4 (on linux).  I need to install v0.3 on some machine to try this. Keeping up with compatibility, etc. is a big job.  I don't remember for sure, but I think `@inline` may not be defined in Julia 0.3
