### ISSUE TITLE
W(exp(x))

### ISSUE THREAD

**Issue by gestay** [jlapeyre/LambertW.jl#5]
Hello:
Some equations have solutions like: x = W(exp(a)).
The numerical evaluation of that expression may cause overflow or round-off errors.

In this paper http://arxiv.org/pdf/0810.5564.pdf, there are a two functions defined to solve this kind of problems.
Do you think that this package can be extended to support the functions defined in the equations (11) and (15) of that paper?

Thanks

**Comment by jlapeyre** [comment]
These functions don't seem to help in computing W(x). E.g. the first computes W(exp(x)).  You can't use this to get W(x) for large arguments without resorting to a high-precision data type, which is what the paper intends to avoid.

Still, it may be reasonable to implement and export these "omega" functions for applications such as the Colebrook equation, which is the subject of the paper.
