### ISSUE TITLE
lambertw(0.1,-1) doesn't work

### ISSUE THREAD

**Issue by sunbubble** [jlapeyre/LambertW.jl#7]
Somehow I have to write z = 0.1 + 0im for it to work. Seems silly... I'm on Julia 0.6

```
DomainError:

Stacktrace:
 [1] _lambertwkm1(::Float64) at /Users/bla/.julia/v0.6/LambertW/src/LambertW.jl:76
 [2] lambertw(::Float64, ::Int64) at /Users/bla/.julia/v0.6/LambertW/src/LambertW.jl:113
```

**Comment by jlapeyre** [comment]
This behavior is consistent with other math functions:

```
julia> log(-1.0)
ERROR: DomainError:
log will only return a complex result if called with a complex argument. Try log(complex(x)).
```

This helps the compiler reason about types. But, I am not certain that the current implementation of lambertw  and of the interference system are able to take advantage of this.

**Comment by sunbubble** [comment]
Duh, I totally missed the domain.
Thanks, nevermind

**Comment by jlapeyre** [comment]
No problem.  I was in the process of editing the last post when you responded. The gist is that, even if `lambertw` cannot be optimized this way now, it might be in the future. And if many people are using it by then, the optimization can't be supported without breaking the API.
